using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

// Generates Source/Strings.g.cs from Languages/English/Keyed/*.xml (English = baseline).
//
// Usage:
//   dotnet run --project Tools/GenStrings                 (writes Source/Strings.g.cs)
//   dotnet run --project Tools/GenStrings -- --check      (exit 1 if out of date, writes nothing)
//
// Key format: CPG_<path...>_<member>_<Kind>  where Kind is Label | Description | Message.
//   Label/Description -> static string property
//   Message           -> method, one NamedArgument per {0},{1},... placeholder
//   path segments      -> nested static classes

var repoRoot = FindRepoRoot();
var keyedDir = Path.Combine(repoRoot, "Languages", "English", "Keyed");
var outFile = Path.Combine(repoRoot, "Source", "Strings.g.cs");
var check = args.Contains("--check");

var kinds = new[]
{
    new Kind("Label", "Labels"),
    new Kind("Description", "Descriptions"),
    new Kind("Message", "Messages"),
};

var roots = kinds.Select(k => new Node(k.ClassName)).ToArray();

foreach (var file in Directory.GetFiles(keyedDir, "*.xml").OrderBy(f => f, StringComparer.Ordinal))
{
    foreach (var el in XDocument.Load(file).Root!.Elements())
    {
        var key = el.Name.LocalName;                 // e.g. CPG_Age_AgeCurve_Label
        var parts = key.Split('_');
        if (parts.Length < 3 || parts[0] != "CPG") continue;

        var suffix = parts[^1];
        var ki = Array.FindIndex(kinds, k => k.Suffix == suffix);
        if (ki < 0) continue;

        // parts: CPG | <path...> | <member> | <suffix>
        var mid = parts[1..^1];
        var member = mid[^1];
        var path = mid[..^1];

        var node = roots[ki];
        foreach (var seg in path) node = node.Child(seg);

        var argCount = 0;
        foreach (Match m in Regex.Matches(el.Value, @"\{(\d+)\}"))
            argCount = Math.Max(argCount, int.Parse(m.Groups[1].Value) + 1);

        node.Members.Add(new Member(member, key, suffix == "Message", argCount));
    }
}

var sb = new StringBuilder();
void Line(string s = "") => sb.Append(s).Append('\n');

Line("// <auto-generated />");
Line("// Generated from Languages/English/Keyed/*.xml by Tools/GenStrings. Do not edit by hand.");
Line("using Verse;");
Line();
Line("namespace RW_CustomPawnGeneration");
Line("{");
Line("\tpublic static partial class Strings");
Line("\t{");
foreach (var root in roots) Emit(root, 2);
Line("\t}");
Line("}");

var content = sb.ToString();

if (check)
{
    var current = File.Exists(outFile) ? File.ReadAllText(outFile).Replace("\r\n", "\n") : "";
    if (current == content)
    {
        Console.WriteLine("Strings.g.cs is up to date.");
        return 0;
    }
    Console.Error.WriteLine("Strings.g.cs is OUT OF DATE. Run: dotnet run --project Tools/GenStrings");
    return 1;
}

File.WriteAllText(outFile, content);
Console.WriteLine($"Wrote {outFile}");
return 0;

void Emit(Node node, int depth)
{
    var pad = new string('\t', depth);
    Line($"{pad}public static class {node.Name}");
    Line($"{pad}{{");

    var members = node.Members.OrderBy(m => m.Name, StringComparer.Ordinal).ToArray();
    for (var i = 0; i < members.Length; i++)
    {
        var m = members[i];
        if (m.IsMessage && m.Args > 0)
        {
            var ps = string.Join(", ", Enumerable.Range(0, m.Args).Select(a => $"NamedArgument a{a}"));
            var xs = string.Join(", ", Enumerable.Range(0, m.Args).Select(a => $"a{a}"));
            Line($"{pad}\tpublic static string {m.Name}({ps}) =>");
            Line($"{pad}\t\t\"{m.Key}\".Translate({xs});");
        }
        else
        {
            Line($"{pad}\tpublic static string {m.Name} => \"{m.Key}\".Translate();");
        }
        if (i < members.Length - 1) Line();
    }

    foreach (var child in node.Children.OrderBy(c => c.Name, StringComparer.Ordinal))
    {
        Line();
        Emit(child, depth + 1);
    }

    Line($"{pad}}}");
    Line();
}

static string FindRepoRoot()
{
    var dir = new DirectoryInfo(AppContext.BaseDirectory);
    while (dir != null && !Directory.Exists(Path.Combine(dir.FullName, "Languages")))
        dir = dir.Parent;
    if (dir == null)
        throw new DirectoryNotFoundException("Could not locate repo root (no 'Languages' folder found above the executable).");
    return dir.FullName;
}

record Kind(string Suffix, string ClassName);

record Member(string Name, string Key, bool IsMessage, int Args);

class Node(string name)
{
    public string Name { get; } = name;
    public List<Member> Members { get; } = new();
    public List<Node> Children { get; } = new();

    public Node Child(string n)
    {
        var c = Children.FirstOrDefault(x => x.Name == n);
        if (c == null) { c = new Node(n); Children.Add(c); }
        return c;
    }
}
