// <auto-generated />
// Generated from Languages/English/Keyed/*.xml by Tools/GenStrings. Do not edit by hand.
using Verse;

namespace RW_CustomPawnGeneration
{
	public static partial class Strings
	{
		public static class Labels
		{
			public static string AdvancedMode => "CPG_AdvancedMode_Label".Translate();

			public static string CPGName => "CPG_CPGName_Label".Translate();

			public static string CopyTo => "CPG_CopyTo_Label".Translate();

			public static string CustomAging => "CPG_CustomAging_Label".Translate();

			public static string Edit => "CPG_Edit_Label".Translate();

			public static string GlobalConfig => "CPG_GlobalConfig_Label".Translate();

			public static string No => "CPG_No_Label".Translate();

			public static string Reset => "CPG_Reset_Label".Translate();

			public static string ResetAll => "CPG_ResetAll_Label".Translate();

			public static string Search => "CPG_Search_Label".Translate();

			public static string ShowConfig => "CPG_ShowConfig_Label".Translate();

			public static string UngenderedParent => "CPG_UngenderedParent_Label".Translate();

			public static string UseRaceSpecific => "CPG_UseRaceSpecific_Label".Translate();

			public static string Yes => "CPG_Yes_Label".Translate();

			public static class Age
			{
				public static string AgeCurve => "CPG_Age_AgeCurve_Label".Translate();

				public static string AgeTick => "CPG_Age_AgeTick_Label".Translate();

				public static string HasAgeTick => "CPG_Age_HasAgeTick_Label".Translate();

				public static string HasMaxAge => "CPG_Age_HasMaxAge_Label".Translate();

				public static string HasMinAge => "CPG_Age_HasMinAge_Label".Translate();

				public static string MaxAge => "CPG_Age_MaxAge_Label".Translate();

				public static string MaxAgeChrono => "CPG_Age_MaxAgeChrono_Label".Translate();

				public static string MinAge => "CPG_Age_MinAge_Label".Translate();

				public static string MinAgeSoft => "CPG_Age_MinAgeSoft_Label".Translate();
			}

		}

		public static class Descriptions
		{
			public static string AdvancedMode => "CPG_AdvancedMode_Description".Translate();

			public static string CustomAging => "CPG_CustomAging_Description".Translate();

			public static string GlobalConfig => "CPG_GlobalConfig_Description".Translate();

			public static string ResetAll => "CPG_ResetAll_Description".Translate();

			public static string UngenderedParent => "CPG_UngenderedParent_Description".Translate();

			public static string UseRaceSpecific => "CPG_UseRaceSpecific_Description".Translate();

			public static class Age
			{
				public static string AgeCurve => "CPG_Age_AgeCurve_Description".Translate();

				public static string HasAgeTick => "CPG_Age_HasAgeTick_Description".Translate();

				public static string HasMaxAge => "CPG_Age_HasMaxAge_Description".Translate();

				public static string HasMinAge => "CPG_Age_HasMinAge_Description".Translate();

				public static string MaxAgeChrono => "CPG_Age_MaxAgeChrono_Description".Translate();

				public static string MinAgeSoft => "CPG_Age_MinAgeSoft_Description".Translate();
			}

		}

		public static class Messages
		{
			public static string Reset(NamedArgument a0) =>
				"CPG_Reset_Message".Translate(a0);
		}

	}
}
