// <auto-generated />
// Generated from Languages/English/Keyed/*.xml by Tools/GenStrings. Do not edit by hand.
using Verse;

namespace RW_CustomPawnGeneration
{
	public static partial class Strings
	{
		public static class Labels
		{
			public static string AdvancedMode => "CPG_AdvancedMode_Label".Translate();

			public static string CPGName => "CPG_CPGName_Label".Translate();

			public static string CopyTo => "CPG_CopyTo_Label".Translate();

			public static string CustomAging => "CPG_CustomAging_Label".Translate();

			public static string Edit => "CPG_Edit_Label".Translate();

			public static string GlobalConfig => "CPG_GlobalConfig_Label".Translate();

			public static string No => "CPG_No_Label".Translate();

			public static string Reset => "CPG_Reset_Label".Translate();

			public static string ResetAll => "CPG_ResetAll_Label".Translate();

			public static string Search => "CPG_Search_Label".Translate();

			public static string ShowConfig => "CPG_ShowConfig_Label".Translate();

			public static string UngenderedParent => "CPG_UngenderedParent_Label".Translate();

			public static string UseRaceSpecific => "CPG_UseRaceSpecific_Label".Translate();

			public static string Yes => "CPG_Yes_Label".Translate();

			public static class Age
			{
				public static string AgeCurve => "CPG_Age_AgeCurve_Label".Translate();

				public static string AgeTick => "CPG_Age_AgeTick_Label".Translate();

				public static string HasAgeTick => "CPG_Age_HasAgeTick_Label".Translate();

				public static string HasMaxAge => "CPG_Age_HasMaxAge_Label".Translate();

				public static string HasMinAge => "CPG_Age_HasMinAge_Label".Translate();

				public static string MaxAge => "CPG_Age_MaxAge_Label".Translate();

				public static string MaxAgeChrono => "CPG_Age_MaxAgeChrono_Label".Translate();

				public static string MinAge => "CPG_Age_MinAge_Label".Translate();

				public static string MinAgeSoft => "CPG_Age_MinAgeSoft_Label".Translate();
			}


			public static class Body
			{
				public static string FilterBody => "CPG_Body_FilterBody_Label".Translate();
			}


			public static class Combo
			{
				public static string Disabled => "CPG_Combo_Disabled_Label".Translate();

				public static string Enabled => "CPG_Combo_Enabled_Label".Translate();

				public static string HeaderTip => "CPG_Combo_HeaderTip_Label".Translate();

				public static string UseGlobalConfig => "CPG_Combo_UseGlobalConfig_Label".Translate();
			}


			public static class Copy
			{
				public static string Apply => "CPG_Copy_Apply_Label".Translate();
			}


			public static class Gender
			{
				public static string Female => "CPG_Gender_Female_Label".Translate();

				public static string Male => "CPG_Gender_Male_Label".Translate();

				public static string ModifyAggressively => "CPG_Gender_ModifyAggressively_Label".Translate();

				public static string OverrideGender => "CPG_Gender_OverrideGender_Label".Translate();

				public static string SeparateGender => "CPG_Gender_SeparateGender_Label".Translate();

				public static string UnforcedGender => "CPG_Gender_UnforcedGender_Label".Translate();
			}


			public static class Hediff
			{
				public static string NoBodyPart => "CPG_Hediff_NoBodyPart_Label".Translate();
			}


			public static class Section
			{
				public static string Age => "CPG_Section_Age_Label".Translate();

				public static string Body => "CPG_Section_Body_Label".Translate();

				public static string Gender => "CPG_Section_Gender_Label".Translate();

				public static string Hediff => "CPG_Section_Hediff_Label".Translate();

				public static string Traits => "CPG_Section_Traits_Label".Translate();
			}


			public static class Traits
			{
				public static string Blocked => "CPG_Traits_Blocked_Label".Translate();

				public static string Forced => "CPG_Traits_Forced_Label".Translate();

				public static string Normal => "CPG_Traits_Normal_Label".Translate();

				public static string OverrideTraits => "CPG_Traits_OverrideTraits_Label".Translate();
			}

		}

		public static class Descriptions
		{
			public static string AdvancedMode => "CPG_AdvancedMode_Description".Translate();

			public static string CustomAging => "CPG_CustomAging_Description".Translate();

			public static string GlobalConfig => "CPG_GlobalConfig_Description".Translate();

			public static string ResetAll => "CPG_ResetAll_Description".Translate();

			public static string UngenderedParent => "CPG_UngenderedParent_Description".Translate();

			public static string UseRaceSpecific => "CPG_UseRaceSpecific_Description".Translate();

			public static class Age
			{
				public static string AgeCurve => "CPG_Age_AgeCurve_Description".Translate();

				public static string HasAgeTick => "CPG_Age_HasAgeTick_Description".Translate();

				public static string HasMaxAge => "CPG_Age_HasMaxAge_Description".Translate();

				public static string HasMinAge => "CPG_Age_HasMinAge_Description".Translate();

				public static string MaxAgeChrono => "CPG_Age_MaxAgeChrono_Description".Translate();

				public static string MinAgeSoft => "CPG_Age_MinAgeSoft_Description".Translate();
			}


			public static class Body
			{
				public static string BodyFix => "CPG_Body_BodyFix_Description".Translate();

				public static string FilterBody => "CPG_Body_FilterBody_Description".Translate();
			}


			public static class Copy
			{
				public static string Info => "CPG_Copy_Info_Description".Translate();
			}


			public static class Gender
			{
				public static string ModifyAggressively => "CPG_Gender_ModifyAggressively_Description".Translate();

				public static string OverrideGender => "CPG_Gender_OverrideGender_Description".Translate();

				public static string SeparateGender => "CPG_Gender_SeparateGender_Description".Translate();

				public static string UnforcedGender => "CPG_Gender_UnforcedGender_Description".Translate();
			}


			public static class Traits
			{
				public static string Info => "CPG_Traits_Info_Description".Translate();

				public static string OverrideTraits => "CPG_Traits_OverrideTraits_Description".Translate();

				public static string Reset => "CPG_Traits_Reset_Description".Translate();
			}

		}

		public static class Messages
		{
			public static string BodyTypeNotFiltered => "CPG_BodyTypeNotFiltered_Message".Translate();

			public static string Reset(NamedArgument a0) =>
				"CPG_Reset_Message".Translate(a0);
		}

	}
}
